export const maxDuration = 60;
import connectDB from "@/config/db";
import Chat from "@/models/Chat";
import { getAuth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import OpenAI from "openai";

// Initialize OpenAI client with DeepSeek API key and base URL
const openai = new OpenAI({
    baseURL: 'https://api.deepseek.com/v1',  
    apiKey: process.env.DEEPSEEK_API_KEY,
    dangerouslyAllowBrowser: false,
    defaultHeaders: {
        'Content-Type': 'application/json',
    }
});

// Mock responses for when the API is unavailable
const getMockResponse = (prompt) => {
    // Normalize the prompt for easier matching
    const lowerPrompt = prompt.toLowerCase().trim();
    console.log("Processing prompt for mock response:", lowerPrompt);
    
    // First check for specific personality queries
    if (lowerPrompt.includes('virat') || lowerPrompt.includes('kohli') || lowerPrompt.includes('virat kohli')) {
        console.log("Matched Virat Kohli query, returning dedicated response");
        return "Virat Kohli is one of cricket's most celebrated figures and among India's greatest sportspersons. Here's a comprehensive profile:\n\n**Career Highlights**:\n- **International Debut**: Made his ODI debut in 2008 against Sri Lanka\n- **Test Cricket**: Debuted in 2011, has scored over 8000 Test runs with 27+ centuries\n- **ODI Dominance**: One of the fastest to reach 10,000 ODI runs, with 40+ centuries\n- **T20 Cricket**: Holds records for most runs in T20 World Cups and IPL\n- **Captaincy**: Led India from 2013 (T20Is), 2017 (all formats) to 2022, one of India's most successful captains\n\n**Achievements & Records**:\n- Only cricketer to average 50+ in all three formats simultaneously\n- Holds the record for fastest to reach milestones of 8000, 9000, 10000, 11000 ODI runs\n- Second highest century-maker in international cricket after Sachin Tendulkar\n- ICC Cricketer of the Year multiple times (2017, 2018)\n- Led India to their first Test series win in Australia (2018-19)\n\n**Playing Style**:\n- Known for his aggressive batting, exceptional fitness, and chase mastery\n- Orthodox technique combined with ability to play innovative shots\n- Remarkable ability to pace innings and handle pressure situations\n- Exceptional fielder with quick reflexes and accurate throwing arm\n\n**Personal Life & Influence**:\n- Born on November 5, 1988, in Delhi, India\n- Married to Bollywood actress Anushka Sharma in 2017, with whom he has a daughter\n- Transformed fitness standards in Indian cricket with his rigorous regimen\n- Businessman with interests in fashion (WROGN), restaurants, and fitness centers\n- One of the world's most marketable athletes with numerous endorsements\n\n**Legacy & Impact**:\n- Revolutionized Indian cricket's approach to fitness and professionalism\n- Inspiration to millions of young cricketers in India and worldwide\n- Known for his passionate on-field demeanor and sportsmanship\n- Philanthropist who established the Virat Kohli Foundation to help underprivileged children\n\nVirat Kohli's combination of technical excellence, mental strength, and leadership abilities has established him as one of cricket's all-time greats, with potentially many more achievements to come in his career.";
    }
    
    // IPL related responses
    else if (lowerPrompt.includes('ipl') || lowerPrompt.includes('cricket') || lowerPrompt.includes('indian premier league')) {
        if (lowerPrompt.includes('tell about') || lowerPrompt.includes('what is')) {
            return "The Indian Premier League (IPL) is a professional Twenty20 cricket league in India contested during March or April and May of every year by ten teams representing different Indian cities or states. The IPL was founded by the Board of Control for Cricket in India (BCCI) in 2008.\n\nIt is one of the most popular cricket leagues in the world, with high attendance and global TV viewership. The IPL has helped grow cricket's popularity, brought substantial revenues to the BCCI, and allowed players from around the world to showcase their talents and earn significant income.\n\nTeams in the IPL include Chennai Super Kings, Mumbai Indians, Royal Challengers Bangalore, Kolkata Knight Riders, Delhi Capitals, Punjab Kings, Rajasthan Royals, Sunrisers Hyderabad, Gujarat Titans, and Lucknow Super Giants.";
        } else if (lowerPrompt.includes('team') || lowerPrompt.includes('teams')) {
            return "The IPL currently has 10 teams:\n\n1. Chennai Super Kings (CSK)\n2. Mumbai Indians (MI)\n3. Royal Challengers Bangalore (RCB)\n4. Kolkata Knight Riders (KKR)\n5. Delhi Capitals (DC)\n6. Punjab Kings (PBKS)\n7. Rajasthan Royals (RR)\n8. Sunrisers Hyderabad (SRH)\n9. Gujarat Titans (GT)\n10. Lucknow Super Giants (LSG)\n\nEach team represents different cities or states across India. The most successful teams in IPL history are Mumbai Indians (with 5 titles) and Chennai Super Kings (with 5 titles).";
        } else if (lowerPrompt.includes('player') || lowerPrompt.includes('players') || lowerPrompt.includes('batsman') || lowerPrompt.includes('bowler')) {
            return "The IPL has featured many legendary cricket players over the years. Some notable players include:\n\n1. Virat Kohli - Highest run-scorer in IPL history\n2. MS Dhoni - Iconic captain who led CSK to multiple titles\n3. Rohit Sharma - Successful captain of Mumbai Indians\n4. Chris Gayle - Known for explosive batting and highest individual score\n5. AB de Villiers - Famous for innovative shots and consistent performances\n6. Sunil Narine - Outstanding spin bowler and pinch hitter\n7. Jasprit Bumrah - Premier fast bowler\n8. Lasith Malinga - Highest wicket-taker in IPL history\n\nPlayers are acquired through an auction system where teams bid for players within their salary cap limits.";
        } else if (lowerPrompt.includes('history') || lowerPrompt.includes('began') || lowerPrompt.includes('started')) {
            return "The IPL was founded in 2008 by the Board of Control for Cricket in India (BCCI), inspired by the success of the Twenty20 format. The inaugural season was won by Rajasthan Royals under Shane Warne's captaincy.\n\nThe league's creation followed India's victory in the 2007 ICC World Twenty20 and was designed to promote cricket in India and globally. Over the years, it has transformed into one of the most-watched sporting events worldwide and has revolutionized cricket with its blend of sports and entertainment.\n\nThe IPL has grown from an 8-team tournament to a 10-team competition, with the addition of Gujarat Titans and Lucknow Super Giants in 2022. The tournament has had various title sponsors, including DLF, Pepsi, Vivo, and Tata.";
        } else if (lowerPrompt.includes('format') || lowerPrompt.includes('rules') || lowerPrompt.includes('how is it played')) {
            return "The IPL follows the Twenty20 (T20) cricket format, which is a shorter version of cricket compared to Test matches and One Day Internationals. Here are the key aspects of the IPL format:\n\n1. Each team plays 14 matches in a double round-robin format (playing each team twice)\n2. The top 4 teams qualify for the playoffs\n3. Playoffs consist of two Qualifiers and an Eliminator, leading to the Final\n4. Each match has 20 overs per side (120 balls)\n5. Powerplay restrictions apply in the first 6 overs\n6. Each bowler can bowl a maximum of 4 overs per match\n7. Teams can field a maximum of 4 overseas players in their playing XI\n\nThe fast-paced format makes for exciting matches that typically last around 3-4 hours.";
        } else if (lowerPrompt.includes('money') || lowerPrompt.includes('salary') || lowerPrompt.includes('revenue') || lowerPrompt.includes('auction')) {
            return "The IPL is one of the richest sports leagues in the world. Key financial aspects include:\n\n1. Broadcasting rights: The 2023-2027 media rights were sold for $6.2 billion\n2. Franchise values: Top teams like Mumbai Indians and Chennai Super Kings are valued at over $1 billion\n3. Player auctions: Some players command prices exceeding $2 million for a single season\n4. Salary cap: Each team has a limit on how much they can spend on players\n5. Revenue streams: Include ticket sales, merchandise, sponsorships, and broadcast rights\n\nThe IPL has created substantial economic value and has made cricket a lucrative career option for players worldwide. The auction process, where teams bid for players, is a unique aspect that adds excitement and strategic elements to team building.";
        } else {
            return "The Indian Premier League (IPL) is one of the biggest cricket tournaments in the world. It's a Twenty20 cricket league founded in 2008 that features ten franchise teams from different Indian cities. The tournament combines world-class cricket with entertainment elements like celebrity owners and performances.\n\nMatches are played in a fast-paced T20 format, with each game lasting about 3-4 hours. The IPL has transformed cricket, creating lucrative opportunities for players and bringing new audiences to the sport. Teams like Mumbai Indians, Chennai Super Kings, and Royal Challengers Bangalore have massive fan followings.\n\nWhat specific aspect of the IPL would you like to know more about?";
        }
    }

    // General knowledge responses
    else if (lowerPrompt.includes('who are you') || lowerPrompt.includes('your name') || lowerPrompt.includes('about you')) {
        return "I'm ThinkNest, an AI assistant designed to help answer your questions and provide information. While I'm currently operating in offline mode with limited capabilities, I can still assist with basic information on various topics. In the future, when fully operational, I'll be able to provide more comprehensive and up-to-date information!";
    }
    else if (lowerPrompt.includes('hello') || lowerPrompt.includes('hi')) {
        return "Hello! I'm ThinkNest, your AI assistant. How can I help you today?";
    } 
    else if (lowerPrompt.includes('help')) {
        return "I'm here to help! You can ask me questions about various topics like sports, history, technology, and more. I can provide information, explanations, and answer your queries to the best of my abilities. What would you like to know about?";
    } 
    else if (lowerPrompt.includes('thank')) {
        return "You're welcome! Feel free to ask if you need anything else.";
    }
    else if (lowerPrompt.includes('weather') || lowerPrompt.includes('temperature') || lowerPrompt.includes('forecast')) {
        return "I'm currently operating in offline mode, so I can't access real-time weather data. When fully operational, I'll be able to provide current weather information and forecasts for any location. For now, I recommend checking a weather service or app for the most up-to-date information.";
    }
    else if (lowerPrompt.includes('movie') || lowerPrompt.includes('film') || lowerPrompt.includes('watch')) {
        return "While I'm in offline mode, I can still recommend some critically acclaimed films across different genres:\n\n1. Drama: The Shawshank Redemption, Parasite, The Godfather\n2. Science Fiction: Inception, The Matrix, Interstellar\n3. Comedy: The Grand Budapest Hotel, Superbad, Bridesmaids\n4. Action: Die Hard, Mad Max: Fury Road, The Dark Knight\n5. Animation: Spider-Man: Across the Spider-Verse, Toy Story, Spirited Away\n\nWhen I'm fully operational, I can provide more personalized recommendations and information about recent releases.";
    }
    else if (lowerPrompt.includes('code') || lowerPrompt.includes('program') || lowerPrompt.includes('javascript') || lowerPrompt.includes('python')) {
        return "Here's a simple example of code in JavaScript that creates a function to calculate the factorial of a number:\n\n```javascript\nfunction factorial(n) {\n  if (n === 0 || n === 1) {\n    return 1;\n  }\n  return n * factorial(n - 1);\n}\n\n// Example usage\nconst number = 5;\nconsole.log(`Factorial of ${number} is ${factorial(number)}`);\n// Output: Factorial of 5 is 120\n```\n\nThis is a recursive implementation. The factorial of a number is the product of all positive integers less than or equal to that number. For example, factorial of 5 is 5 × 4 × 3 × 2 × 1 = 120.";
    }

    // Technology related responses
    else if (lowerPrompt.includes('ai') || lowerPrompt.includes('artificial intelligence') || lowerPrompt.includes('machine learning')) {
        return "Artificial Intelligence (AI) refers to computer systems designed to perform tasks that typically require human intelligence. Key aspects of AI include:\n\n1. **Machine Learning**: Algorithms that improve through experience\n2. **Neural Networks**: Computing systems inspired by the human brain\n3. **Natural Language Processing**: Enabling computers to understand human language\n4. **Computer Vision**: Allowing machines to interpret visual information\n\nAI has applications across numerous fields including healthcare (disease diagnosis), finance (fraud detection), transportation (self-driving vehicles), and everyday consumer applications like voice assistants.\n\nRecent advances in generative AI, like large language models, have created systems capable of generating human-like text, images, and even code. While AI offers tremendous benefits, it also raises important ethical considerations around privacy, bias, job displacement, and autonomous decision-making.";
    }
    else if (lowerPrompt.includes('blockchain') || lowerPrompt.includes('bitcoin') || lowerPrompt.includes('crypto')) {
        return "Blockchain is a distributed database or ledger technology that allows multiple participants to keep identical, shared records. Key features include:\n\n1. **Decentralization**: No single entity controls the entire network\n2. **Immutability**: Once recorded, data cannot be altered retroactively\n3. **Transparency**: All transactions are publicly viewable\n4. **Security**: Cryptographic techniques protect the integrity of data\n\nThe most well-known application of blockchain is cryptocurrencies like Bitcoin, which was created in 2009 by an anonymous person or group known as Satoshi Nakamoto. Beyond cryptocurrencies, blockchain has potential applications in supply chain management, voting systems, digital identity verification, and smart contracts.\n\nWhile blockchain offers advantages in terms of security and transparency, challenges include scalability, energy consumption (particularly for proof-of-work systems), regulatory uncertainty, and integration with existing systems.";
    }
    else if (lowerPrompt.includes('smartphone') || lowerPrompt.includes('iphone') || lowerPrompt.includes('android')) {
        return "Smartphones are mobile devices that combine cellular telephone capabilities with computer functionality. They typically feature:\n\n1. **Operating Systems**: Primarily Android (developed by Google) and iOS (developed by Apple)\n2. **Touchscreen Interfaces**: Allowing intuitive interaction\n3. **Internet Connectivity**: Via cellular networks and Wi-Fi\n4. **App Ecosystems**: Enabling users to extend functionality through software applications\n\nThe modern smartphone era began with the introduction of the iPhone by Apple in 2007, which revolutionized the industry with its touchscreen interface and app store concept. Android, released by Google in 2008, has become the world's most widely used mobile operating system.\n\nSmartphones have transformed how people communicate, work, and access information, essentially putting powerful computers in billions of pockets worldwide. Recent technological advances include improved cameras, 5G connectivity, augmented reality capabilities, and increasing use of AI for various functions.";
    }

    // Science related responses
    else if (lowerPrompt.includes('space') || lowerPrompt.includes('universe') || lowerPrompt.includes('astronomy')) {
        return "Space, also known as outer space, refers to the vast void that exists beyond Earth and between celestial bodies. Our understanding of space has evolved dramatically over the past century.\n\n**Key concepts in astronomy include**:\n\n1. **The Solar System**: Our cosmic neighborhood consists of the Sun, eight planets (Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune), dwarf planets, moons, asteroids, and comets\n\n2. **Stars and Galaxies**: Stars are massive, luminous spheres of plasma. Our Sun is a star in the Milky Way galaxy, which contains between 100-400 billion stars\n\n3. **The Big Bang Theory**: The prevailing cosmological model suggests the universe began approximately 13.8 billion years ago from an extremely hot and dense singularity\n\n4. **Black Holes**: Regions of spacetime where gravity is so strong that nothing, not even light, can escape\n\nRecent space exploration highlights include the James Webb Space Telescope, Mars rovers, the study of exoplanets, and the development of commercial spaceflight by companies like SpaceX, Blue Origin, and Virgin Galactic.";
    }
    else if (lowerPrompt.includes('climate') || lowerPrompt.includes('global warming') || lowerPrompt.includes('environment')) {
        return "Climate change refers to long-term shifts in temperatures and weather patterns. While these changes can occur naturally, since the 1800s, human activities have been the main driver of climate change, primarily due to the burning of fossil fuels like coal, oil, and gas, which produces heat-trapping gases.\n\n**Key aspects include**:\n\n1. **Greenhouse Effect**: Gases like carbon dioxide, methane, and nitrous oxide trap heat in the Earth's atmosphere\n\n2. **Global Warming**: The observed increase in Earth's average temperature over extended periods\n\n3. **Impacts**: Rising sea levels, increased frequency and intensity of extreme weather events, biodiversity loss, and threats to food security\n\n4. **Mitigation Strategies**: Transitioning to renewable energy, improving energy efficiency, sustainable agriculture, and reforestation\n\nInternational efforts to address climate change include the Paris Agreement, which aims to limit global warming to well below 2°C, preferably to 1.5°C, compared to pre-industrial levels. Achieving these goals requires significant reductions in greenhouse gas emissions and adaptation to already occurring changes.";
    }
    else if (lowerPrompt.includes('dna') || lowerPrompt.includes('gene') || lowerPrompt.includes('genetics')) {
        return "DNA (deoxyribonucleic acid) is the hereditary material in humans and almost all other organisms. Nearly every cell in a person's body has the same DNA.\n\n**Key concepts in genetics include**:\n\n1. **Structure**: DNA consists of two strands coiled around each other in a double helix, composed of four chemical bases: adenine (A), guanine (G), cytosine (C), and thymine (T)\n\n2. **Genes**: Segments of DNA that contain instructions for building proteins, which perform most of the critical functions in cells and the body\n\n3. **Genome**: The complete set of genetic information in an organism\n\n4. **Genetic Engineering**: Technologies that allow direct manipulation of genetic material to alter an organism's characteristics\n\nAdvances in genetic research have led to breakthroughs like the Human Genome Project, gene therapy for treating diseases, CRISPR gene editing technology, and personalized medicine based on individual genetic profiles. These developments offer tremendous potential benefits but also raise important ethical considerations around genetic privacy, enhancement, and equity.";
    }

    // History and culture related responses
    else if (lowerPrompt.includes('world war') || lowerPrompt.includes('ww2') || lowerPrompt.includes('wwii')) {
        return "World War II (1939-1945) was the deadliest global conflict in human history, involving many of the world's nations divided into two opposing military alliances: the Allies and the Axis.\n\n**Key aspects include**:\n\n1. **Origins**: The war emerged from unresolved tensions from World War I, the Great Depression, the rise of fascism, and aggressive expansionism by Nazi Germany, Imperial Japan, and Fascist Italy\n\n2. **Major Theaters**: The European Theater (including the Eastern Front between Germany and the Soviet Union), the Pacific Theater, North Africa, and the Middle East\n\n3. **The Holocaust**: The genocide of six million Jews and millions of others by Nazi Germany\n\n4. **Atomic Bombings**: The first and only use of nuclear weapons in warfare when the United States bombed Hiroshima and Nagasaki in Japan\n\n5. **Outcome**: Allied victory, the creation of the United Nations, the beginning of the Cold War, decolonization, and profound social and political changes globally\n\nWorld War II resulted in an estimated 70-85 million fatalities and fundamentally altered the political alignment and social structure of the world. Its legacy continues to influence geopolitics, international relations, and collective memory worldwide.";
    }
    else if (lowerPrompt.includes('art') || lowerPrompt.includes('music') || lowerPrompt.includes('literature')) {
        return "The arts encompass a diverse range of human activities involving creative imagination and expression, including visual arts, performing arts, and literature.\n\n**Key movements and concepts include**:\n\n1. **Visual Arts**: From prehistoric cave paintings to Renaissance masterpieces to modern abstract expressionism and digital art\n\n2. **Music**: Spanning classical compositions, folk traditions, jazz, rock, pop, hip-hop, electronic music, and countless other genres across cultures\n\n3. **Literature**: Encompassing poetry, drama, novels, and other written works that have explored the human condition throughout history\n\n4. **Performing Arts**: Including theater, dance, film, and other forms of embodied expression\n\nThroughout history, the arts have served as means of cultural expression, social commentary, spiritual practice, entertainment, and personal fulfillment. They reflect the values, beliefs, and experiences of societies while also challenging conventions and inspiring new perspectives. Digital technology has transformed how art is created, distributed, and experienced, opening new possibilities while raising questions about authenticity, ownership, and access.";
    }

    // Current topics
    else if (lowerPrompt.includes('social media') || lowerPrompt.includes('facebook') || lowerPrompt.includes('instagram') || lowerPrompt.includes('tiktok')) {
        return "Social media platforms are interactive digital technologies that facilitate the creation and sharing of information, ideas, interests, and other forms of expression through virtual communities and networks.\n\n**Key aspects include**:\n\n1. **Major Platforms**: Facebook (Meta), Instagram, Twitter, TikTok, LinkedIn, YouTube, Snapchat, and others, each with distinct features and user demographics\n\n2. **Impact**: Transformed how people communicate, consume information, form communities, and express themselves\n\n3. **Business Model**: Most platforms operate on advertising revenue, collecting user data to deliver targeted advertisements\n\n4. **Concerns**: Privacy issues, misinformation spread, addiction and mental health impacts, cyberbullying, filter bubbles, and algorithmic bias\n\nSocial media has become deeply integrated into modern life, with billions of users worldwide. While it offers benefits like connection across distances, information access, and new forms of creative expression, there are growing discussions about its regulation, ethical use, and long-term social impacts. Recent trends include the rise of short-form video content, augmented reality features, and increased scrutiny from regulators and the public.";
    }
    else if (lowerPrompt.includes('health') || lowerPrompt.includes('exercise') || lowerPrompt.includes('nutrition')) {
        return "Health encompasses physical, mental, and social well-being, not merely the absence of disease or infirmity.\n\n**Key components of health include**:\n\n1. **Physical Health**: Influenced by nutrition, physical activity, sleep, and avoiding harmful substances\n   - Balanced diet with adequate proteins, carbohydrates, fats, vitamins, and minerals\n   - Regular exercise (150+ minutes of moderate activity weekly recommended)\n   - 7-9 hours of quality sleep for adults\n\n2. **Mental Health**: Emotional, psychological, and social well-being\n   - Stress management through techniques like mindfulness and meditation\n   - Social connection and community engagement\n   - Professional help when needed for conditions like depression and anxiety\n\n3. **Preventive Care**: Regular check-ups, vaccinations, and screenings\n\nCurrent health trends include personalized medicine based on genetic profiles, digital health technologies like wearables and telemedicine, focus on gut health and microbiome, and holistic approaches that recognize the interconnection between physical and mental well-being. The COVID-19 pandemic has also highlighted the importance of public health infrastructure and global cooperation in addressing health challenges.";
    }

    // Additional educational and learning responses
    else if (lowerPrompt.includes('learn') || lowerPrompt.includes('course') || lowerPrompt.includes('study') || lowerPrompt.includes('education')) {
        return "There are many excellent resources for learning online. Here are some recommendations based on different learning approaches:\n\n**Free Online Platforms**:\n- **Khan Academy**: Comprehensive lessons in math, science, and humanities\n- **Coursera**: University courses with free audit options\n- **edX**: Courses from institutions like Harvard and MIT\n- **freeCodeCamp**: In-depth coding curriculum with certifications\n- **YouTube**: Channels like Crash Course, MIT OpenCourseWare, and many subject specialists\n\n**Paid Learning Platforms**:\n- **Udemy**: Wide range of affordable courses on practical skills\n- **Masterclass**: High-quality instruction from world-renowned experts\n- **LinkedIn Learning**: Professional and business skills\n- **Skillshare**: Creative and practical skills with project-based learning\n\n**Learning Methods**:\n- **Spaced Repetition**: Review information at increasing intervals\n- **Pomodoro Technique**: 25-minute focused sessions with short breaks\n- **Active Recall**: Test yourself instead of passively reviewing material\n- **Feynman Technique**: Explain concepts in simple terms to ensure understanding\n\nThe most effective approach varies by individual learning style, subject matter, and goals. What specific topic are you interested in learning?";
    }

    // Travel and places information
    else if (lowerPrompt.includes('travel') || lowerPrompt.includes('vacation') || lowerPrompt.includes('visit') || lowerPrompt.includes('tourism')) {
        return "Travel enriches our lives through exposure to new cultures, environments, and experiences. Here are some popular destinations and travel tips:\n\n**Popular Destinations**:\n\n1. **Europe**:\n   - **Paris, France**: Eiffel Tower, Louvre Museum, charming streets\n   - **Rome, Italy**: Colosseum, Vatican City, incredible cuisine\n   - **Barcelona, Spain**: Stunning architecture, beaches, vibrant culture\n\n2. **Asia**:\n   - **Kyoto, Japan**: Traditional temples, gardens, and cuisine\n   - **Bali, Indonesia**: Beautiful beaches, spirituality, and affordability\n   - **Bangkok, Thailand**: Bustling markets, temples, and street food\n\n3. **North America**:\n   - **New York City, USA**: Iconic skyline, Broadway, diverse neighborhoods\n   - **Vancouver, Canada**: Natural beauty with mountains and ocean\n   - **Mexico City, Mexico**: Rich history, art scene, and cuisine\n\n**Travel Tips**:\n\n- Book flights 2-3 months in advance for best prices\n- Consider shoulder seasons (just before or after peak season) for fewer crowds\n- Learn basic phrases in the local language\n- Get travel insurance for unexpected situations\n- Use apps like Google Maps offline and currency converters\n\nWhen fully operational, I could provide more specific recommendations based on your preferences, budget, and travel dates. Do you have a specific destination in mind?";
    }

    // Cooking and recipes
    else if (lowerPrompt.includes('recipe') || lowerPrompt.includes('cook') || lowerPrompt.includes('food') || lowerPrompt.includes('meal')) {
        return "Cooking at home can be rewarding, economical, and healthier than eating out. Here's a versatile recipe that's relatively easy to make:\n\n**Quick Pasta with Garlic and Olive Oil (Aglio e Olio)**\n\n**Ingredients**:\n- 8 oz (225g) spaghetti or pasta of choice\n- 4-6 cloves garlic, thinly sliced\n- 1/4 cup extra virgin olive oil\n- 1/4 teaspoon red pepper flakes (optional)\n- 1/4 cup fresh parsley, chopped\n- Salt and pepper to taste\n- Grated Parmesan cheese (optional)\n\n**Instructions**:\n\n1. Bring a large pot of salted water to a boil. Cook pasta according to package directions until al dente.\n2. While pasta cooks, heat olive oil in a large pan over medium-low heat.\n3. Add sliced garlic and red pepper flakes, cooking until garlic is fragrant and lightly golden (2-3 minutes). Be careful not to burn the garlic.\n4. Reserve 1/2 cup of pasta water, then drain pasta.\n5. Add pasta to the pan with garlic oil, tossing to coat. Add a splash of reserved pasta water to create a light sauce.\n6. Remove from heat, stir in fresh parsley, and season with salt and pepper.\n7. Serve immediately, topped with grated Parmesan if desired.\n\nThis dish takes about 15 minutes to prepare and is highly customizable. You can add ingredients like cherry tomatoes, spinach, or pre-cooked chicken for variation.\n\nWould you like more recipes or cooking tips for beginners?";
    }

    // Entertainment, hobbies and activities
    else if (lowerPrompt.includes('hobby') || lowerPrompt.includes('bored') || lowerPrompt.includes('free time') || lowerPrompt.includes('activities')) {
        return "Hobbies and activities can provide enjoyment, skill development, and sometimes even social connections. Here are some ideas across different interests:\n\n**Low-Cost Hobbies**:\n- **Reading**: Libraries offer free access to books, ebooks, and audiobooks\n- **Hiking/Walking**: Explore local parks and nature areas\n- **Drawing/Sketching**: Requires minimal supplies to start\n- **Gardening**: Start small with herbs in containers\n- **Cooking**: Experiment with new recipes\n\n**Creative Pursuits**:\n- **Photography**: Even smartphone photography can be rewarding\n- **Writing**: Journaling, poetry, short stories, or blogging\n- **Music**: Learning an instrument or digital music production\n- **DIY Crafts**: Upcycling, papercraft, or jewelry making\n\n**Physical Activities**:\n- **Yoga**: Follow free online classes to start\n- **Cycling**: Explore your area on two wheels\n- **Dancing**: Many styles can be practiced at home\n- **Rock Climbing**: Indoor gyms make this accessible\n\n**Tech & Learning**:\n- **Coding**: Many free resources to learn programming\n- **3D Modeling**: Free software like Blender is powerful\n- **Language Learning**: Apps like Duolingo offer free basics\n- **Podcasting**: Share your interests with others\n\nThe best hobby is one that matches your interests and circumstances. What types of activities do you typically enjoy?";
    }

    // Personal finance and money management
    else if (lowerPrompt.includes('money') || lowerPrompt.includes('finance') || lowerPrompt.includes('invest') || lowerPrompt.includes('budget')) {
        return "Personal finance is an essential life skill. Here are some fundamental principles and tips:\n\n**Budgeting Basics**:\n1. **Track Spending**: Know where your money goes by categorizing expenses\n2. **50/30/20 Rule**: Aim to spend 50% on needs, 30% on wants, and save 20%\n3. **Emergency Fund**: Build savings to cover 3-6 months of essential expenses\n4. **Debt Management**: Prioritize paying down high-interest debt\n\n**Investment Fundamentals**:\n1. **Retirement Accounts**: Maximize contributions to tax-advantaged accounts like 401(k)s and IRAs\n2. **Index Funds**: Low-cost way to invest in the broader market\n3. **Diversification**: Spread investments across different asset classes to manage risk\n4. **Compound Interest**: Start early to benefit from growth over time\n\n**Money-Saving Tips**:\n1. **Automate Savings**: Set up automatic transfers to savings accounts\n2. **Reduce Recurring Expenses**: Review subscriptions and services regularly\n3. **Comparison Shop**: Research before major purchases\n4. **Energy Efficiency**: Lower utility bills through mindful usage\n\n**Important Note**: This is general information and not personalized financial advice. Personal finance situations vary widely, and what works for one person may not be appropriate for another.\n\nIs there a specific aspect of personal finance you'd like to know more about?";
    }

    // Jokes and humor
    else if (lowerPrompt.includes('joke') || lowerPrompt.includes('funny') || lowerPrompt.includes('laugh') || lowerPrompt.includes('humor')) {
        const jokes = [
            "Why don't scientists trust atoms? Because they make up everything!",
            "What do you call a fake noodle? An impasta!",
            "Why did the scarecrow win an award? Because he was outstanding in his field!",
            "How does a penguin build its house? Igloos it together!",
            "Why don't eggs tell jokes? They'd crack each other up!",
            "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
            "I told my wife she was drawing her eyebrows too high. She looked surprised!",
            "What do you call a parade of rabbits hopping backwards? A receding hare-line!",
            "Why don't skeletons fight each other? They don't have the guts!",
            "What's orange and sounds like a parrot? A carrot!"
        ];
        const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
        return `Here's a joke for you:\n\n${randomJoke}\n\nI hope that brought a smile to your face! Would you like another one?`;
    }

    // Motivational and inspirational content
    else if (lowerPrompt.includes('motivation') || lowerPrompt.includes('inspire') || lowerPrompt.includes('encouragement') || lowerPrompt.includes('quote')) {
        const quotes = [
            "\"The future belongs to those who believe in the beauty of their dreams.\" —Eleanor Roosevelt",
            "\"Success is not final, failure is not fatal: It is the courage to continue that counts.\" —Winston Churchill",
            "\"Hardships often prepare ordinary people for an extraordinary destiny.\" —C.S. Lewis",
            "\"You are never too old to set another goal or to dream a new dream.\" —C.S. Lewis",
            "\"The only limit to our realization of tomorrow will be our doubts of today.\" —Franklin D. Roosevelt",
            "\"The way to get started is to quit talking and begin doing.\" —Walt Disney",
            "\"Don't watch the clock; do what it does. Keep going.\" —Sam Levenson",
            "\"Believe you can and you're halfway there.\" —Theodore Roosevelt",
            "\"You don't have to be great to start, but you have to start to be great.\" —Zig Ziglar",
            "\"It always seems impossible until it's done.\" —Nelson Mandela"
        ];
        const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
        return `Here's an inspirational quote that might resonate with you:\n\n${randomQuote}\n\nRemember that motivation often follows action rather than preceding it. Starting small with consistent steps toward your goals can build momentum and lead to lasting change. What specific area are you seeking motivation in?`;
    }

    // Tech support and troubleshooting
    else if (lowerPrompt.includes('computer') || lowerPrompt.includes('laptop') || lowerPrompt.includes('fix') || lowerPrompt.includes('troubleshoot') || lowerPrompt.includes('error')) {
        return "Here are some general computer troubleshooting steps that resolve many common issues:\n\n**Basic Troubleshooting Steps**:\n\n1. **Restart Your Device**: This simple step clears temporary memory and reloads all services\n\n2. **Check Connections**: Ensure all cables are securely connected and power sources are working\n\n3. **Update Software**: Install available operating system and application updates\n\n4. **Clear Cache/Cookies**: For browser issues, clearing cache and cookies often helps\n\n5. **Run Antivirus Scan**: Scan for malware that might be causing problems\n\n6. **Check System Resources**: Use Task Manager (Windows) or Activity Monitor (Mac) to identify resource-heavy processes\n\n**For Windows-Specific Issues**:\n- Run the built-in troubleshooters (Settings > Update & Security > Troubleshoot)\n- Use System File Checker (sfc /scannow in Command Prompt as admin)\n- Check Event Viewer for specific error codes\n\n**For Mac-Specific Issues**:\n- Reset PRAM/NVRAM (restart and hold Command+Option+P+R)\n- Run First Aid in Disk Utility\n- Boot in Safe Mode to identify extension conflicts\n\nWithout specific details about your issue, these are general recommendations. Could you provide more information about the problem you're experiencing?";
    }

    // Writing assistance
    else if (lowerPrompt.includes('write') || lowerPrompt.includes('essay') || lowerPrompt.includes('email') || lowerPrompt.includes('letter')) {
        return "Effective writing is a valuable skill in both personal and professional contexts. Here are some general writing tips:\n\n**General Writing Principles**:\n\n1. **Clarity**: Be clear and direct; avoid unnecessary jargon or complexity\n2. **Purpose**: Identify your main point or goal before you begin\n3. **Audience**: Consider who will read your writing and what they need\n4. **Structure**: Organize with a beginning, middle, and end\n5. **Revise**: Good writing comes from rewriting and editing\n\n**Email Writing Tips**:\n- Use clear subject lines\n- Keep messages concise and focused\n- Include a specific action request if needed\n- Maintain professional tone even in casual settings\n\n**Essay Writing Process**:\n1. Brainstorm and research your topic\n2. Create an outline with main points\n3. Write a strong thesis statement\n4. Develop paragraphs with topic sentences and supporting evidence\n5. Craft an introduction and conclusion\n6. Revise for content, structure, and grammar\n\n**Common Writing Mistakes to Avoid**:\n- Passive voice overuse\n- Vague or abstract language\n- Run-on sentences\n- Inconsistent tense or point of view\n- Relying too heavily on adverbs\n\nFor more specific guidance, I would need to know what type of content you're working on. What are you trying to write?";
    }

    // Common knowledge questions (like simple facts)
    else if (lowerPrompt.includes('how many') || lowerPrompt.includes('what is the') || lowerPrompt.includes('when did') || lowerPrompt.includes('where is')) {
        if (lowerPrompt.includes('president') || lowerPrompt.includes('prime minister')) {
            return "While I'm operating in offline mode, I can provide some general information about world leaders and governments.\n\nThe President of the United States serves a 4-year term and can be elected for a maximum of two terms. The U.S. has had 46 presidents throughout its history.\n\nIn parliamentary systems like the UK, Canada, and India, the Prime Minister is the head of government, while a monarch or president serves as head of state.\n\nFor the most current information about who is currently serving as president or prime minister in a specific country, you would need to check an up-to-date source, as this information changes with elections and political developments.\n\nWhen I'm fully operational, I'll be able to provide you with the most current information about world leaders.";
        } else if (lowerPrompt.includes('planet') || lowerPrompt.includes('solar system')) {
            return "There are eight recognized planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Pluto was previously classified as the ninth planet but was reclassified as a dwarf planet by the International Astronomical Union (IAU) in 2006.\n\nThe planets in order from closest to farthest from the Sun are:\n1. Mercury - The smallest planet, closest to the Sun\n2. Venus - The hottest planet due to its dense atmosphere\n3. Earth - Our home planet, the only known world with liquid water on its surface\n4. Mars - The red planet, with polar ice caps and ancient river valleys\n5. Jupiter - The largest planet, a gas giant with a strong magnetic field\n6. Saturn - Famous for its distinctive ring system\n7. Uranus - Rotates on its side with an extreme axial tilt\n8. Neptune - The windiest planet with strong blue coloration\n\nBeyond Neptune, there are several dwarf planets including Pluto, Eris, Haumea, Makemake, and Ceres.";
        } else if (lowerPrompt.includes('element') || lowerPrompt.includes('periodic table')) {
            return "The periodic table contains 118 confirmed elements, with elements 1-94 occurring naturally (though some only in trace amounts) and elements 95-118 being synthetic.\n\nThe most abundant element in the universe is hydrogen, making up about 75% of all normal matter. On Earth, the most abundant element by mass is oxygen, which makes up about 46% of the Earth's crust, 89% of the world's oceans, and 23% of the atmosphere.\n\nElements are organized in the periodic table by atomic number (number of protons), with rows representing periods and columns representing groups with similar properties. Notable groups include:\n- Group 1: Alkali metals (highly reactive)\n- Group 17: Halogens (also highly reactive)\n- Group 18: Noble gases (mostly inert)\n\nThe most recently confirmed elements (as of my knowledge cutoff) are extremely unstable synthetic elements like Oganesson (element 118) and Tennessine (element 117).";
        } else if (lowerPrompt.includes('country') || lowerPrompt.includes('nation')) {
            return "There are 193 member states in the United Nations, plus observer states like the Holy See (Vatican) and Palestine. The exact number of countries in the world varies depending on recognition criteria.\n\nThe largest country by land area is Russia, covering approximately 17.1 million square kilometers (6.6 million square miles) and spanning 11 time zones.\n\nThe smallest internationally recognized country is Vatican City at just 0.49 square kilometers (0.19 square miles).\n\nThe most populous countries are:\n1. China - approximately 1.4 billion people\n2. India - approximately 1.3 billion people\n3. United States - approximately 330 million people\n4. Indonesia - approximately 270 million people\n\nThe newest countries include South Sudan (2011) and Kosovo (which declared independence in 2008, though its status remains disputed by some nations).\n\nNote that population figures are approximate and change over time. When I'm fully operational, I can provide more precise and current figures.";
        } else {
            return "I'd be happy to answer your factual question, but since I'm currently operating in offline mode with limited capabilities, I can only provide general information rather than specific up-to-date facts on all topics. When fully operational, I'll be able to access current information to answer your specific question accurately.\n\nIf you're asking about general knowledge topics like science, history, or geography, I can provide basic information based on my training. Please feel free to ask a more specific question, and I'll do my best to help with the information I have available.";
        }
    }

    // Life advice and self-improvement
    else if (lowerPrompt.includes('advice') || lowerPrompt.includes('tips') || lowerPrompt.includes('improve') || lowerPrompt.includes('better')) {
        return "Personal growth and self-improvement are ongoing journeys. Here are some general principles that many find helpful:\n\n**For Overall Well-being**:\n\n1. **Prioritize Sleep**: Quality sleep affects everything from cognitive function to emotional regulation\n\n2. **Practice Mindfulness**: Being present can reduce stress and improve focus; even 5 minutes of meditation daily can help\n\n3. **Cultivate Relationships**: Meaningful social connections are strongly linked to happiness and longevity\n\n4. **Embrace Failure**: View setbacks as learning opportunities rather than permanent defeats\n\n**For Productivity**:\n\n1. **Set SMART Goals**: Specific, Measurable, Achievable, Relevant, Time-bound\n\n2. **Use Time Blocking**: Schedule specific periods for different types of work\n\n3. **Apply the 2-Minute Rule**: If a task takes less than 2 minutes, do it immediately\n\n4. **Practice Deep Work**: Allocate distraction-free time for challenging tasks\n\n**For Learning**:\n\n1. **Embrace a Growth Mindset**: Believe abilities can be developed through dedication and hard work\n\n2. **Teach Others**: Explaining concepts reinforces your understanding\n\n3. **Apply Knowledge**: Using information in practical ways improves retention\n\nRemember that small, consistent actions often lead to more sustainable change than dramatic overhauls. What specific area of life are you looking to improve?";
    }

    // Explanations about common concepts
    else if (lowerPrompt.includes('explain') || lowerPrompt.includes('what is') || lowerPrompt.includes('how does') || lowerPrompt.includes('why is')) {
        return "I'd be happy to explain concepts in various fields. Since I'm operating in offline mode, I can provide general explanations about many common topics. For very specific or technical questions, my explanations will be more general.\n\nSome examples of concepts I can explain include:\n\n- Scientific principles (like gravity, evolution, or photosynthesis)\n- Historical events and movements\n- Technical concepts (like how the internet works or what is blockchain)\n- Cultural practices and traditions\n- Basic principles in fields like psychology, economics, or philosophy\n\nTo provide you with a helpful explanation, I'd need to know which specific concept you're interested in learning about. Could you please specify what you'd like me to explain?";
    }

    // Famous personalities responses
    else if (lowerPrompt.includes('famous') || lowerPrompt.includes('celebrity') || lowerPrompt.includes('personalities') || lowerPrompt.includes('person')) {
        // Check for Virat Kohli specific queries first
        if (lowerPrompt.includes('virat') || lowerPrompt.includes('kohli') || lowerPrompt.includes('virat kohli')) {
            return "Virat Kohli is one of cricket's most celebrated figures and among India's greatest sportspersons. Here's a comprehensive profile:\n\n**Career Highlights**:\n- **International Debut**: Made his ODI debut in 2008 against Sri Lanka\n- **Test Cricket**: Debuted in 2011, has scored over 8000 Test runs with 27+ centuries\n- **ODI Dominance**: One of the fastest to reach 10,000 ODI runs, with 40+ centuries\n- **T20 Cricket**: Holds records for most runs in T20 World Cups and IPL\n- **Captaincy**: Led India from 2013 (T20Is), 2017 (all formats) to 2022, one of India's most successful captains\n\n**Achievements & Records**:\n- Only cricketer to average 50+ in all three formats simultaneously\n- Holds the record for fastest to reach milestones of 8000, 9000, 10000, 11000 ODI runs\n- Second highest century-maker in international cricket after Sachin Tendulkar\n- ICC Cricketer of the Year multiple times (2017, 2018)\n- Led India to their first Test series win in Australia (2018-19)\n\n**Playing Style**:\n- Known for his aggressive batting, exceptional fitness, and chase mastery\n- Orthodox technique combined with ability to play innovative shots\n- Remarkable ability to pace innings and handle pressure situations\n- Exceptional fielder with quick reflexes and accurate throwing arm\n\n**Personal Life & Influence**:\n- Born on November 5, 1988, in Delhi, India\n- Married to Bollywood actress Anushka Sharma in 2017, with whom he has a daughter\n- Transformed fitness standards in Indian cricket with his rigorous regimen\n- Businessman with interests in fashion (WROGN), restaurants, and fitness centers\n- One of the world's most marketable athletes with numerous endorsements\n\n**Legacy & Impact**:\n- Revolutionized Indian cricket's approach to fitness and professionalism\n- Inspiration to millions of young cricketers in India and worldwide\n- Known for his passionate on-field demeanor and sportsmanship\n- Philanthropist who established the Virat Kohli Foundation to help underprivileged children\n\nVirat Kohli's combination of technical excellence, mental strength, and leadership abilities has established him as one of cricket's all-time greats, with potentially many more achievements to come in his career.";
        }
        
        // Continue with the existing conditions for Indian personalities
        // Indian personalities detection
        else if (lowerPrompt.includes('india') || lowerPrompt.includes('indian')) {
            // Sports personalities from India
            if (lowerPrompt.includes('sport') || lowerPrompt.includes('cricket') || lowerPrompt.includes('athlete')) {
                return "India has produced many remarkable sports personalities across various disciplines. Here are some notable figures:\n\n**Cricket**:\n- **Sachin Tendulkar**: Often called the 'God of Cricket', he holds numerous batting records including most runs and centuries in international cricket\n- **Virat Kohli**: Modern batting great and former captain known for his aggressive style and fitness standards\n- **MS Dhoni**: Led India to World Cup victories in 2007 (T20) and 2011 (ODI), known for his calm demeanor and finishing abilities\n- **Sunil Gavaskar**: Legendary opener who was the first to reach 10,000 Test runs\n- **Kapil Dev**: All-rounder who led India to its first World Cup victory in 1983\n\n**Other Sports**:\n- **PT Usha**: 'Queen of Indian Track and Field', narrowly missed an Olympic medal in 1984\n- **Saina Nehwal & PV Sindhu**: Badminton stars who have won Olympic medals (Sindhu - silver in 2016, bronze in 2020; Nehwal - bronze in 2012)\n- **Abhinav Bindra**: Won India's first individual Olympic gold medal in 10m air rifle shooting (2008)\n- **Mary Kom**: Six-time World Amateur Boxing champion and Olympic bronze medalist\n- **Neeraj Chopra**: First Indian to win Olympic gold in athletics with his javelin throw victory in 2021\n- **Sania Mirza**: Most successful Indian tennis player, former doubles world No. 1\n- **Vishwanathan Anand**: Five-time World Chess Champion who put India on the global chess map\n\nThese athletes have not only achieved sporting excellence but have also inspired generations of Indians to pursue sports professionally.";
            }
            // Political figures from India
            else if (lowerPrompt.includes('politic') || lowerPrompt.includes('leader') || lowerPrompt.includes('prime minister') || lowerPrompt.includes('president')) {
                return "India has been shaped by many influential political leaders throughout its history. Here are some prominent Indian political personalities:\n\n**Freedom Movement Era**:\n- **Mahatma Gandhi**: Leader of India's non-violent independence movement against British rule and pioneer of Satyagraha (truth-force)\n- **Jawaharlal Nehru**: India's first Prime Minister (1947-1964) who established democratic institutions and a mixed economy\n- **Sardar Vallabhbhai Patel**: 'Iron Man of India' who integrated over 560 princely states into the union\n- **Subhas Chandra Bose**: Founded the Indian National Army, advocated for armed resistance against British rule\n- **B.R. Ambedkar**: Chairman of the Constitution drafting committee and social reformer who fought against caste discrimination\n\n**Post-Independence Leaders**:\n- **Indira Gandhi**: India's only female Prime Minister (served 1966-1977 and 1980-1984), known for decisive leadership and the Emergency period\n- **A.P.J. Abdul Kalam**: Aerospace scientist who served as President (2002-2007) and inspired millions with his vision for India\n- **Atal Bihari Vajpayee**: First non-Congress Prime Minister to complete a full term (1998-2004), poet and respected orator\n- **Narendra Modi**: Current Prime Minister (since 2014) known for bold economic reforms and strong foreign policy\n- **Lal Bahadur Shastri**: Second Prime Minister known for his slogan 'Jai Jawan, Jai Kisan' (Hail the soldier, Hail the farmer)\n\nThese leaders have contributed significantly to India's political landscape, governance structure, and international standing through different periods of the nation's history.";
            }
            // Entertainment and film personalities from India
            else if (lowerPrompt.includes('bollywood') || lowerPrompt.includes('actor') || lowerPrompt.includes('actress') || lowerPrompt.includes('film') || lowerPrompt.includes('movie') || lowerPrompt.includes('cinema')) {
                return "India has a rich cinematic tradition with many celebrated film personalities across different film industries. Here are some notable figures:\n\n**Bollywood (Hindi Cinema)**:\n- **Amitabh Bachchan**: Iconic actor with a career spanning over 50 years, known as the 'Angry Young Man' and later reinventing himself multiple times\n- **Shah Rukh Khan**: 'King Khan' known for romantic roles and global stardom\n- **Aamir Khan**: Known for perfectionism and socially relevant films like 'Dangal' and 'Lagaan'\n- **Dilip Kumar**: Tragedy King of Hindi cinema who influenced generations of actors\n- **Madhuri Dixit**: Dancing icon and versatile actress of the 80s and 90s\n- **Deepika Padukone**: Leading contemporary actress known for diverse roles\n- **Sridevi**: First female superstar who dominated across multiple language films\n\n**Regional Cinema**:\n- **Rajinikanth**: Superstar of Tamil cinema with an almost mythical fan following\n- **Kamal Haasan**: Versatile Tamil actor known for pushing creative boundaries\n- **Mohanlal & Mammootty**: Malayalam cinema legends known for natural acting\n- **Prabhas**: Telugu actor who gained nationwide fame with 'Baahubali'\n- **Prosenjit Chatterjee**: Leading figure in Bengali cinema\n\n**Directors & Filmmakers**:\n- **Satyajit Ray**: Oscar-winning director whose 'Apu Trilogy' is considered among the greatest films ever made\n- **Raj Kapoor**: Actor-director known as 'The Greatest Showman of Indian Cinema'\n- **Sanjay Leela Bhansali**: Known for grand, visually stunning productions\n- **Mani Ratnam**: Acclaimed Tamil director known for socio-political themes\n- **S.S. Rajamouli**: Director of the blockbuster 'Baahubali' series and 'RRR'\n\nIndian cinema is diverse, with strong regional industries in Tamil, Telugu, Malayalam, Bengali, Marathi, and other languages, each with their own celebrated personalities.";
            }
            // Business and entrepreneurship from India
            else if (lowerPrompt.includes('business') || lowerPrompt.includes('entrepreneur') || lowerPrompt.includes('company') || lowerPrompt.includes('startup')) {
                return "India has produced many visionary business leaders and entrepreneurs who have built global enterprises. Here are some notable figures:\n\n**Industrial Pioneers**:\n- **JRD Tata**: Built the Tata Group into India's largest conglomerate and started India's first airline\n- **Dhirubhai Ambani**: Founded Reliance Industries from humble beginnings, revolutionized equity investing for middle-class Indians\n- **G.D. Birla**: Key industrialist who supported the independence movement and built a diversified business empire\n\n**Contemporary Business Leaders**:\n- **Mukesh Ambani**: Chairman of Reliance Industries, among the world's wealthiest individuals, transforming telecommunications through Jio\n- **Ratan Tata**: Former chairman who globalized the Tata Group through acquisitions like Jaguar Land Rover\n- **Azim Premji**: Built Wipro into an IT giant and pioneered corporate philanthropy in India\n- **Narayana Murthy**: Co-founder of Infosys, helped establish India as a global IT powerhouse\n- **Kumar Mangalam Birla**: Chairman of the Aditya Birla Group, diversified into telecommunications and retail\n\n**New-Age Entrepreneurs**:\n- **Ritesh Agarwal**: Founded OYO Rooms at age 19, disrupting the hospitality industry\n- **Byju Raveendran**: Created BYJU'S, one of the world's most valuable edtech companies\n- **Vijay Shekhar Sharma**: Founder of Paytm, pioneered digital payments in India\n- **Falguni Nayar**: Former investment banker who founded Nykaa, becoming one of India's self-made female billionaires\n- **Deepinder Goyal & Pankaj Chaddah**: Co-founders of Zomato, transforming food delivery\n\nThese business leaders have not only created economic value but have also influenced India's development trajectory and inspired a new generation of entrepreneurs.";
            }
            // Scientists and thinkers from India
            else if (lowerPrompt.includes('science') || lowerPrompt.includes('scientist') || lowerPrompt.includes('inventor') || lowerPrompt.includes('academic')) {
                return "India has a rich tradition of scientific thought and has produced many distinguished scientists and intellectuals. Here are some notable figures:\n\n**Historical Pioneers**:\n- **Aryabhata**: 5th-century mathematician and astronomer who calculated π, described the Earth's rotation, and developed the place-value system\n- **Brahmagupta**: Introduced the concept of zero as a number and negative numbers in the 7th century\n- **Srinivasa Ramanujan**: Self-taught mathematical genius whose contributions to number theory, infinite series, and continued fractions were revolutionary\n\n**Modern Scientists**:\n- **C.V. Raman**: Won the 1930 Nobel Prize in Physics for the 'Raman Effect', a phenomenon in light scattering\n- **Homi J. Bhabha**: Father of India's nuclear program who established premier research institutions\n- **Vikram Sarabhai**: Founder of India's space program and established the Physical Research Laboratory\n- **A.P.J. Abdul Kalam**: Aerospace scientist known as the 'Missile Man of India' who later became President\n- **S. Chandrasekhar**: Nobel laureate in Physics for his work on the evolution of stars\n- **Har Gobind Khorana**: Nobel Prize winner for research on the interpretation of the genetic code\n- **Venkatraman Ramakrishnan**: Nobel laureate in Chemistry for studies of the structure and function of the ribosome\n\n**Contemporary Scientists**:\n- **Tessy Thomas**: Known as the 'Missile Woman of India', led the development of the Agni-IV and Agni-V missiles\n- **K. Radhakrishnan**: Former ISRO chairman who oversaw the Mars Orbiter Mission (Mangalyaan)\n- **Gagandeep Kang**: First Indian woman to be elected Fellow of the Royal Society, known for rotavirus vaccine work\n- **Soumya Swaminathan**: Chief Scientist at WHO, known for her work on tuberculosis and HIV\n\nIndia continues to make significant contributions to global science and technology, with strengths in areas like space technology, pharmaceuticals, renewable energy, and information technology.";
            }
            // Default response for Indian personalities
            else {
                return "India has produced many notable personalities who have made significant contributions across various fields:\n\n**Freedom Fighters & Political Leaders**:\n- **Mahatma Gandhi**: Pioneer of non-violent civil disobedience\n- **Jawaharlal Nehru**: First Prime Minister of independent India\n- **Sardar Vallabhbhai Patel**: 'Iron Man of India' who united the princely states\n- **B.R. Ambedkar**: Chief architect of the Indian Constitution\n\n**Scientists & Thinkers**:\n- **C.V. Raman**: Nobel laureate in Physics for the 'Raman Effect'\n- **A.P.J. Abdul Kalam**: Aerospace scientist and former President\n- **Srinivasa Ramanujan**: Mathematical genius whose intuitive contributions astonished the world\n\n**Arts & Literature**:\n- **Rabindranath Tagore**: First non-European Nobel laureate in Literature\n- **Satyajit Ray**: Acclaimed filmmaker whose work gained international recognition\n- **M.F. Husain**: Celebrated painter known as the 'Picasso of India'\n\n**Business & Industry**:\n- **JRD Tata**: Built the Tata Group into India's largest conglomerate\n- **Dhirubhai Ambani**: Founded Reliance Industries from humble beginnings\n- **N.R. Narayana Murthy**: Co-founder of Infosys, pioneered India's IT revolution\n\n**Sports**:\n- **Sachin Tendulkar**: Considered the greatest cricket batsman of all time\n- **Vishwanathan Anand**: Five-time World Chess Champion\n- **Neeraj Chopra**: Olympic gold medalist in javelin throw\n\nIndian personalities have influenced global thought in philosophy, mathematics, science, arts, and commerce throughout history. Is there a particular field you're interested in learning more about?";
            }
        }
        // Global personalities
        else {
            // Global sports figures
            if (lowerPrompt.includes('sport') || lowerPrompt.includes('athlete') || lowerPrompt.includes('olympic')) {
                return "The world of sports has been shaped by many legendary figures who transcended their disciplines. Here are some of the most influential global sports personalities:\n\n**Football (Soccer)**:\n- **Pelé**: Brazilian icon widely regarded as the greatest footballer ever, three-time World Cup winner\n- **Diego Maradona**: Argentine genius known for the 'Hand of God' and 'Goal of the Century'\n- **Lionel Messi**: Multiple Ballon d'Or winner known for his dribbling and goalscoring\n- **Cristiano Ronaldo**: Portuguese star known for his athleticism, goalscoring, and longevity\n\n**Basketball**:\n- **Michael Jordan**: Transformed the NBA into a global phenomenon, six-time NBA champion\n- **LeBron James**: Modern great known for his all-around game and longevity\n- **Kobe Bryant**: Lakers legend known for his 'Mamba Mentality' and work ethic\n\n**Tennis**:\n- **Roger Federer, Rafael Nadal & Novak Djokovic**: The 'Big Three' who dominated men's tennis for nearly two decades\n- **Serena Williams**: 23-time Grand Slam singles champion, revolutionized women's tennis\n- **Martina Navratilova**: Won 59 Grand Slam titles across singles and doubles\n\n**Track & Field**:\n- **Usain Bolt**: Jamaican sprinter, fastest man in history and 8-time Olympic gold medalist\n- **Carl Lewis**: Dominated sprinting and long jump, winning 9 Olympic gold medals\n\n**Swimming**:\n- **Michael Phelps**: Most decorated Olympian with 28 medals (23 gold)\n- **Katie Ledecky**: Dominant female swimmer with multiple world records\n\n**Boxing**:\n- **Muhammad Ali**: Transcended sports with his boxing skills and activism\n- **Mike Tyson**: Youngest heavyweight champion known for his ferocious style\n\n**Other Notables**:\n- **Wayne Gretzky**: Ice hockey's 'Great One' who revolutionized the game\n- **Tiger Woods**: Transformed golf's popularity and commercial appeal\n- **Simone Biles**: Gymnast who pushed the boundaries of difficulty in women's gymnastics\n\nThese athletes have not only dominated their sports but have also become cultural icons, influenced fashion and media, and often used their platforms for social causes.";
            }
            // Global political leaders
            else if (lowerPrompt.includes('politic') || lowerPrompt.includes('leader') || lowerPrompt.includes('president') || lowerPrompt.includes('minister')) {
                return "Throughout history, certain political leaders have shaped the course of nations and global events. Here are some of the most influential global political figures:\n\n**20th Century Transformative Leaders**:\n- **Winston Churchill**: British Prime Minister who led the UK through World War II\n- **Franklin D. Roosevelt**: US President who implemented the New Deal and led through WWII\n- **Mahatma Gandhi**: Led India's independence movement through non-violent resistance\n- **Nelson Mandela**: Anti-apartheid revolutionary who became South Africa's first black president\n- **Martin Luther King Jr.**: Civil rights leader who advocated for racial equality through non-violence\n\n**Cold War Era Leaders**:\n- **John F. Kennedy**: US President during the Cuban Missile Crisis and early space race\n- **Mikhail Gorbachev**: Last leader of the Soviet Union, implemented glasnost and perestroika\n- **Margaret Thatcher**: UK's first female Prime Minister known as the 'Iron Lady'\n- **Deng Xiaoping**: Chinese leader who introduced market reforms and opened China to the world\n\n**Contemporary Global Leaders**:\n- **Angela Merkel**: Former German Chancellor who led Europe through multiple crises\n- **Barack Obama**: First African American US President\n- **Xi Jinping**: Chinese leader overseeing China's rise as a global power\n- **Jacinda Ardern**: New Zealand PM noted for her handling of crises and compassionate leadership\n\n**Controversial Historical Figures**:\n- **Mao Zedong**: Founded the People's Republic of China, implemented radical reforms\n- **Joseph Stalin**: Soviet leader during WWII, responsible for rapid industrialization and political repression\n\nThese leaders' legacies are complex and often contested, reflecting the challenges of governance and the competing values of their times. Their decisions continue to influence international relations, domestic policies, and political thought worldwide.";
            }
            // Global scientists and inventors
            else if (lowerPrompt.includes('science') || lowerPrompt.includes('scientist') || lowerPrompt.includes('inventor') || lowerPrompt.includes('discover')) {
                return "Scientific progress has been driven by brilliant minds whose discoveries have transformed our understanding of the world. Here are some of the most influential scientists and inventors in history:\n\n**Physics Revolutionaries**:\n- **Albert Einstein**: Developed the theory of relativity, transforming our understanding of space, time, and gravity\n- **Isaac Newton**: Formulated the laws of motion and universal gravitation, invented calculus\n- **Niels Bohr**: Pioneer of quantum theory and atomic structure\n- **Marie Curie**: Only person to win Nobel Prizes in two different scientific fields (Physics and Chemistry)\n- **Stephen Hawking**: Theoretical physicist known for his work on black holes and cosmology\n\n**Biology & Medicine**:\n- **Charles Darwin**: Proposed the theory of evolution by natural selection\n- **Alexander Fleming**: Discovered penicillin, launching the antibiotic era\n- **Rosalind Franklin**: Her X-ray diffraction images were key to discovering DNA's structure\n- **Louis Pasteur**: Developed vaccines and the process of pasteurization\n- **Jane Goodall**: Revolutionary research on chimpanzees that changed our understanding of primates\n\n**Chemistry & Materials**:\n- **Dmitri Mendeleev**: Created the periodic table of elements\n- **Alfred Nobel**: Invented dynamite and established the Nobel Prizes\n- **Tu Youyou**: Discovered artemisinin to treat malaria, saving millions of lives\n\n**Technology & Computing**:\n- **Alan Turing**: Father of theoretical computer science and artificial intelligence\n- **Tim Berners-Lee**: Invented the World Wide Web\n- **Grace Hopper**: Pioneered computer programming and developed COBOL\n- **Nikola Tesla**: Inventor who contributed to the design of the modern AC electricity supply system\n- **Thomas Edison**: Prolific inventor with over 1,000 patents, including the practical electric light bulb\n\n**Earth & Space Sciences**:\n- **Galileo Galilei**: Made foundational contributions to astronomy and physics\n- **Katherine Johnson**: NASA mathematician whose calculations were critical to early US space missions\n- **Rachel Carson**: Her book 'Silent Spring' launched the environmental movement\n\nThese scientists not only made groundbreaking discoveries but often changed entire paradigms of thought, opening new fields of inquiry and transforming how we live.";
            }
            // Global business leaders and entrepreneurs
            else if (lowerPrompt.includes('business') || lowerPrompt.includes('entrepreneur') || lowerPrompt.includes('company') || lowerPrompt.includes('startup')) {
                return "The business world has been shaped by visionary entrepreneurs who built transformative companies and industries. Here are some of the most influential global business leaders:\n\n**Tech Pioneers**:\n- **Steve Jobs**: Co-founder of Apple who revolutionized multiple industries with products like the iPhone\n- **Bill Gates**: Co-founder of Microsoft who helped make personal computing mainstream\n- **Jeff Bezos**: Founded Amazon, transforming retail and creating cloud computing giant AWS\n- **Elon Musk**: Entrepreneur behind Tesla, SpaceX, and multiple innovative ventures\n- **Mark Zuckerberg**: Created Facebook (now Meta), shaping how billions connect online\n- **Jack Ma**: Founder of Alibaba Group, pioneering e-commerce in China\n\n**Industrial & Retail Icons**:\n- **Henry Ford**: Revolutionized manufacturing with the assembly line and affordable automobiles\n- **Walt Disney**: Created an entertainment empire that spans generations\n- **Sam Walton**: Founded Walmart, pioneering modern retail distribution\n- **Oprah Winfrey**: Built a media empire and became one of the world's first black female billionaires\n\n**Finance & Investment**:\n- **Warren Buffett**: Legendary investor known as the 'Oracle of Omaha'\n- **JP Morgan**: Financed industries and shaped modern banking\n- **Ray Dalio**: Founder of the world's largest hedge fund, Bridgewater Associates\n\n**Recent Innovators**:\n- **Brian Chesky, Joe Gebbia & Nathan Blecharczyk**: Co-founders of Airbnb, disrupting hospitality\n- **Reed Hastings**: Co-founder of Netflix, transformed entertainment distribution\n- **Whitney Wolfe Herd**: Founded Bumble, pioneering female-first approach in dating apps\n- **Satoshi Nakamoto**: Pseudonymous creator of Bitcoin and blockchain technology\n\nThese business leaders have not only created immense economic value but have often fundamentally changed how we live, work, and interact. Their approaches to innovation, leadership, and problem-solving continue to influence aspiring entrepreneurs worldwide.";
            }
            // Global artists, musicians, and entertainers
            else if (lowerPrompt.includes('art') || lowerPrompt.includes('music') || lowerPrompt.includes('entertain') || lowerPrompt.includes('actor') || lowerPrompt.includes('actress') || lowerPrompt.includes('singer')) {
                return "The arts have been shaped by extraordinary talents whose creative vision transcended boundaries and defined cultural movements. Here are some of the most influential global figures in arts and entertainment:\n\n**Visual Arts**:\n- **Leonardo da Vinci**: Renaissance polymath whose works like 'Mona Lisa' remain iconic\n- **Pablo Picasso**: Pioneered Cubism and produced over 20,000 works across multiple mediums\n- **Frida Kahlo**: Mexican artist known for her striking self-portraits and cultural imagery\n- **Andy Warhol**: Pop art pioneer who blurred the boundaries between commercial and fine art\n- **Banksy**: Contemporary street artist whose politically charged works generate global attention\n\n**Music Legends**:\n- **Wolfgang Amadeus Mozart**: Prolific classical composer who shaped Western music\n- **The Beatles**: Revolutionary band whose music transformed popular culture\n- **Michael Jackson**: 'King of Pop' known for groundbreaking performances and record sales\n- **Bob Marley**: Brought reggae to a global audience while advocating for social justice\n- **Beyoncé**: Contemporary icon who has redefined music, performance, and cultural influence\n\n**Film & Entertainment**:\n- **Charlie Chaplin**: Silent film pioneer who combined comedy with social commentary\n- **Alfred Hitchcock**: Master of suspense who revolutionized filmmaking techniques\n- **Meryl Streep**: Most Academy Award-nominated actor, known for versatility\n- **Steven Spielberg**: Filmmaker whose works have defined modern blockbuster cinema\n- **Hayao Miyazaki**: Animated film master whose works blend fantasy, environmentalism, and humanism\n\n**Literary Giants**:\n- **William Shakespeare**: Playwright whose works remain the most performed centuries later\n- **Jane Austen**: Author whose novels examining society and gender remain relevant\n- **Gabriel García Márquez**: Pioneer of magical realism, bringing Latin American literature to the world\n- **Toni Morrison**: Nobel Prize-winning author who explored African American experiences\n\n**Performing Arts**:\n- **Mikhail Baryshnikov**: Revolutionary ballet dancer who pushed physical and artistic boundaries\n- **Maria Callas**: Opera singer whose dramatic intensity transformed the art form\n\nThese artists have not only entertained but have challenged conventions, reflected societal truths, and expanded our understanding of human experience through their creative expressions.";
            }
            // Default response for global personalities
            else {
                return "Throughout history, certain individuals have made exceptional contributions that transformed our world. Here are some influential global personalities across different fields:\n\n**Science & Innovation**:\n- **Albert Einstein**: Revolutionized physics with the theory of relativity\n- **Marie Curie**: Pioneer in radioactivity research and first person to win Nobel Prizes in two sciences\n- **Steve Jobs**: Co-founded Apple and transformed multiple industries with innovative products\n- **Tim Berners-Lee**: Invented the World Wide Web, making the internet accessible\n\n**Leadership & Social Change**:\n- **Nelson Mandela**: Anti-apartheid revolutionary who became South Africa's first black president\n- **Mahatma Gandhi**: Led India to independence through non-violent resistance\n- **Martin Luther King Jr.**: Civil rights leader who advocated for racial equality\n- **Malala Yousafzai**: Education activist and youngest Nobel Prize laureate\n\n**Arts & Culture**:\n- **William Shakespeare**: Playwright whose works remain central to Western literature\n- **Pablo Picasso**: Revolutionary artist who co-founded Cubism\n- **The Beatles**: Band that transformed music and popular culture\n- **Oprah Winfrey**: Media executive who built a global platform for conversation\n\n**Sports & Entertainment**:\n- **Muhammad Ali**: Boxing champion and activist who transcended sports\n- **Michael Jordan**: Basketball player who globalized the NBA\n- **Pelé**: Brazilian footballer often regarded as the greatest of all time\n\n**Business & Economics**:\n- **Henry Ford**: Revolutionized manufacturing with the assembly line\n- **Warren Buffett**: Investing legend known as the 'Oracle of Omaha'\n- **Elon Musk**: Entrepreneur behind companies pushing boundaries in space, electric vehicles, and more\n\nThese individuals have not only excelled in their fields but have also shaped how we think, live, and interact with the world. Their legacies continue to inspire new generations. Is there a particular field you're interested in exploring further?";
            }
        }
    }

    else {
        return "I'm currently operating with limited capabilities in offline mode. I can provide basic information on topics like sports (including IPL), general knowledge, and some coding examples. For more specific or complex queries, please try again when the service is fully operational. Is there something specific within these areas I can help you with?";
    }
};

export async function POST(req){
    try {
        const {userId} = getAuth(req)

        // Extract chatId and prompt from the request body
        const { chatId, prompt } = await req.json();

        if(!userId){
            return NextResponse.json({
                success: false,
                message: "User not authenticated",
              });
        }

        // Connect to the database
        await connectDB();
        
        // Find the chat document in the database based on userId and chatId
        const chat = await Chat.findOne({userId, _id: chatId});
        
        if (!chat) {
            return NextResponse.json({
                success: false,
                message: "Chat not found",
            });
        }

        // Create a user message object
        const userPrompt = {
            role: "user",
            content: prompt,
            timestamp: Date.now()
        };

        // Add user message to chat history
        chat.messages.push(userPrompt);
        
        // Prepare messages for the API - we need to format them correctly
        const recentMessages = chat.messages.slice(-10).map(msg => ({
            role: msg.role,
            content: msg.content
        }));

        // TEMPORARY SOLUTION: Skip trying DeepSeek API and use mock responses directly
        console.log("Using mock response for:", prompt);
        
        // Get the mock response directly
        const mockResponseText = getMockResponse(prompt);
        const mockMessage = {
            role: "assistant",
            content: mockResponseText,
            timestamp: Date.now()
        };
        
        // Add mock message to chat
        chat.messages.push(mockMessage);
        await chat.save();
        
        // Return the mock message to the client without warning
        return NextResponse.json({
            success: true, 
            data: mockMessage
        });
    } catch (error) {
        console.error("Server Error:", error);
        return NextResponse.json({ 
            success: false, 
            error: error.message,
            stack: error.stack 
        });
    }
}